### ISSUE TITLE
Breaks undo stack and other weird behaviour

### ISSUE THREAD

**Issue by TeriyakiBomb** [gingerbeardman/Tag-Sync#1]
I'm testing in 11.10, not tried in 12b yet but renaming an element, putting a string inside then trying to undo those changes prevents you from undoing a change, deleting the string also exhibits some weird behavior

https://github.com/user-attachments/assets/d6251ac5-0865-48ef-aba4-bf1834a82ed6

**Comment by gingerbeardman** [comment]
I knew I'd miss something in this quick attempt at solving the problem.

I should have tested it more!

Thanks for the report! I'll do my best to fix it.

**Comment by gingerbeardman** [comment]
OK, I rewrote most of it. 

It's much better, but there are most likely still edge cases I've not considered. 

Let's start new issues for each problem as they arise.

This new code is much more robust and should see us well for some improvements. I've also left the logging in, but disabled, because I have a feeling I'll need it in future.

**Comment by TeriyakiBomb** [comment]
All good my end :) If I come across anything else, I'll let you know

**Comment by gingerbeardman** [comment]
Of the top of my head it doesn't deal to well if you erase opening tag with backspace

https://github.com/gingerbeardman/Tag-Sync/issues/2
